<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            ['product_name' => 'Eyeshadow Pallete', 'product_type' => 'Beauty', 'description' => 'Make your eyes shine with the HiveMind Eyeshadow Palette.', 'price' => '8', 'ingredients' => 'Dawn, Ecru, Slate & Taupe: MICA, CELLULOSE, ROSA MOSCHATA SEED OIL, OCTYLDODECYL STEAROYL STEARATE, CAPRYLYL GLYCOL, ZINC STEARATE, HIPPOPHAE RHAMNOIDES OIL, MAGNESIUM STEARATE, KAOLIN, CAPRYLIC/CAPRIC TRIGLYCERIDE, SODIUM DEHYDROACETATE, PHENOXYETHANOL. MAY CONTAIN/PEUT CONTENIR (+/-): TITANIUM DIOXIDE (CI 77891), IRON OXIDES (CI 77491, CI 77492, CI 77499), FERRIC AMMONIUM FERROCYANIDE (CI 77510), MANGANESE VIOLET (CI 77742), ULTRAMARINES (CI 77007). Shell: MICA, OCTYLDODECYL STEAROYL STEARATE, ROSA MOSCHATA SEED OIL, ZINC STEARATE, CAPRYLYL GLYCOL, HIPPOPHAE RHAMNOIDES OIL, MAGNESIUM STEARATE, CELLULOSE, SODIUM DEHYDROACETATE, PHENOXYETHANOL. MAY CONTAIN/PEUT CONTENIR (+/-): TITANIUM DIOXIDE (CI 77891), IRON OXIDES (CI 77491, CI 77492, CI 77499), ULTRAMARINES (CI 77007). Sandstone: MICA, OCTYLDODECYL STEAROYL STEARATE, ROSA MOSCHATA SEED OIL, SILICA, ZINC STEARATE, CAPRYLYL GLYCOL, HIPPOPHAE RHAMNOIDES OIL, MAGNESIUM STEARATE, CELLULOSE, SODIUM DEHYDROACETATE, PHENOXYETHANOL. MAY CONTAIN/PEUT CONTENIR (+/-): TITANIUM DIOXIDE (CI 77891), IRON OXIDES (CI 77491, CI 77492, CI 77499).', 'directions' => 'null', 'additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Lip Gloss', 'product_type' => 'Beauty', 'description' => 'Spread the word about HiveMind with our Honey-Infused Lip Gloss! With our honey-infused formula, your lips will be moisturised and sweet all day long.', 'price' => '7', 'ingredients' => 'Polyglyceryl-2 Isostearate/Dimer Dilinoleate Copolymer, Dilinoleic Acid/Propanediol Copolymer, Vitis Vinifera (Grape) Seed Oil, Carthamus Tinctorius (Safflower) Seed Oil, Mel (Honey, Miel), Simmondsia Chinensis (Jojoba) Seed Oil, Limnanthes Alba (Meadowfoam) Seed Oil, Helianthus Annuus (Sunflower) Seed Oil, Calendula Officinalis Flower Extract, Oenothera Biennis (Evening Primrose) Oil, Rosa Canina Fruit Oil, Hydrogenated Castor Oil/Sebacic Acid Copolymer, Propolis Cera (Propolis Wax, Cire de Propolis), Tocopheryl Acetate, Tocopherol, Sodium Hyaluronate, Aroma (Flavor), Citrus Aurantium Bergamia (Bergamot) Fruit Extract, Daucus Carota Sativa (Carrot) Root Extract, Mauritia Flexuosa Fruit Oil, Vaccinium Myrtillus Seed Oil, Glucomannan, Ethylhexyl Palmitate, Calcium Sodium Borosilicate, Trihydroxystearin, Tin Oxide, Red 7 Lake (CI 15850), Titanium Dioxide (CI 77891), Citral**, Linalool**, Limonene**. * Honey & Propolis sourced from the Mirsalehi Bee Garden / Miel et Propolis des ruches du jardin Mirsalehi. ** Naturally occurring allergens / Allergènes naturels.', 'directions' => 'null', 'additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Nail Polish (Set of 3)', 'product_type' => 'Beauty', 'description' => 'Your nails have never looked better with our Nail Polish Set.', 'price' => '6', 'ingredients' => 'Butyl Acetate, Ethyl Acetate, Nitrocellulose, Acetyl Tributyl Citrate, Adipic Acid/Neopentyl Glycol/Trimellitic Anhydride Copolymer, Isopropyl Alcohol, Stearalkonium Bentonite, Acrylates Copolymer, N-Butyl Alcohol, Silica, Benzophenone-1, Diacetone Alcohol, Trimethylpentanediyl Dibenzoate, Phosphoric Acid. May contain (+/-): Titanium Dioxide (CI 77891), Iron Oxides (CI 77491, CI 77499), Red 6 Lake (CI 15850), Yellow 5 Lake (CI 19140), Ferric Ferrocyanide (CI 77510), Red 34 Lake (CI 15880), Black 2 (CI 77266 [nano]), Yellow 5 Lake (CI 19140), Ultramarines (CI 77007).', 'directions' => 'null', 'additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => '2-in-1 Highlighter & Blush', 'product_type' => 'Beauty', 'description' => 'A convenient 2-in-1 Highlighter and Blush Palette ready to travel with you in your purse.', 'price' => '7', 'ingredients' => 'DUO GINGER BINGEDIMETHICONE, TALC, ISODODECANE, SYNTHETIC FLUORPHLOGOPITE, CAPRYLIC/CAPRIC TRIGLYCERIDE, PHENOXYETHANOL, TIN OXIDE, BISMUTH OXYCHLORIDE (CI 77163), TITANIUM DIOXIDE (CI 77891), IRON OXIDES (CI 77491), CARMINE (CI 75470), YELLOW 5 LAKE (CI 19140).DUO MOSCOW MULEDIMETHICONE, SYNTHETIC FLUORPHLOGOPITE, ISODODECANE, DIISOSTEARYL MALATE, POLYETHYLENE, ALUMINUM CALCIUM SODIUM SILICATE, TALC, CETYL DIMETHICONE, PHENOXYETHANOL, TIN OXIDE, CALCIUM ALUMINUM BOROSILICATE, SILICA, CALCIUM SODIUM BOROSILICATE, TITANIUM DIOXIDE (CI 77891), BISMUTH OXYCHLORIDE (CI 77163), MANGANESE VIOLET (CI 77742), IRON OXIDES (CI 77491, CI 77492), CARMINE (CI 75470), YELLOW 5 LAKE (CI 19140).', 'directions' => 'null', 'additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Beauty Sponge', 'product_type' => 'Beauty', 'description' => 'Get ready to conquer the day using the HiveMind Beauty Sponge.', 'price' => '5', 'ingredients' => 'Non-latex foam.', 'directions' => 'null', 'additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],

            ['product_name' => 'Vitamin Bee (Vitamin B Gummies)', 'product_type' => 'Health', 'description' => 'Stay healthy and energised throughout your day with our Vitamin Bee gummies!', 'price' => '12', 'ingredients' => 'Glucose Syrup, Sugar, Water, Vitamin C (L-Ascorbic Acid), Gelling Agent (Pectin), Acid (Citric Acid), Maltodextrin, Vitamin E (d-Alpha Tocopheryl Acetate), Colour (Anthocyanins), Acidity Regulator (Sodium Citrate), Coconut Oil, Vitamin A (Retinyl Acetate), Zinc Citrate, Mixed Berry Flavouring, Pantothenic Acid (d-Calcium Pantothenate), Vitamin D3 (Cholecalciferol), Vitamin B6 (Pyridoxine Hydrochloride), Anti-Caking Agent (Carnauba Wax), Vitamin B12 (Cyanocobalamin), Folic Acid (Pteroylmonoglutamic Acid), Vitamin B2 (Riboflavin), Biotin (d-Biotin).', 'directions' => 'null', 'additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Bee Pollen Supplements', 'product_type' => 'Health', 'description' => 'Sprinkle on cereals, mixed in yoghurts or add to smoothies for extra nutrition.', 'price' => '10', 'ingredients' => 'Bee Pollen.', 'directions' => 'Store in a cool dry place away from direct sunlight.', 'additional_info' => 'Warning: this product may cause allergic reactions. Pregnant or lactating women: consult your healthcare professional before use. May contain nuts (made in a factory that occasionally handles nuts). Not suitable for infants under 12 months.', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Propolis Capsules', 'product_type' => 'Health', 'description' => 'Health and Wellness Product: Propolis Capsules', 'price' => '15', 'ingredients' => 'Bee Propolis Extract, Capsule Shell (Hydroxypropyl Methylcellulose), Brewers Yeast (Saccharomyces cerevisiae), Anti-Caking Agents (Magnesium Stearate, Silicon Dioxide).', 'directions' => 'Take 1 Capsule(s) per day, preferably with a meal. Do not exceed stated dose.', 'additional_info' => 'Food supplements must not be used as a substitute for a varied and balanced diet and a healthy lifestyle. If you are pregnant, breastfeeding, taking any medications or under medical supervision, please consult a doctor or healthcare professional before use. Discontinue use and consult a doctor if adverse reactions occur. Keep out of reach of children. Do not use if seal under cap is broken or missing.', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Jar of Honey', 'product_type' => 'Health', 'description' => 'Great for cooking, baking, hot drinks or simply on toast.', 'price' => '7', 'ingredients' => 'Pure Honey (100%).', 'directions' => 'null', 'additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Bee Pollen Powder 250g', 'product_type' => 'Health', 'description' => 'Health and Wellness Product: Pollen Powder 250g', 'price' => '15', 'ingredients' => 'Bee Pollen Powder, Anti-Caking Agent (Silicon Dioxide) (2%). May contain milk, soya, cereals containing gluten, mustard, sesame seeds, sulphur dioxide and sulphites.', 'directions' => 'Bee Pollen Powder can be used at varying amounts, depending on your nutritional requirements. However, we recommend mixing 1 level scoop (15g) with 150ml water in a water bottle. Alternatively add to a homemade juice or smoothie.', 'additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            
            ['product_name' => 'Honey Shampoo', 'product_type' => 'Haircare', 'description' => 'Haircare: Shampoo', 'price' => '7', 'ingredients' => 'Honey, Linseed Mucilage, Sodium Laureth Sulfate, Sunflower Lecithin, Lauryl Betaine, Geranium Oil, Beeswax Absolute, Neroli Oil, Rose Absolute, Bergamot Oil, Citral, Geraniol, Citronellol, Limonene, Linalool, Hydroxycitronellal, Perfume.', 'directions' => 'Massage into hair and scalp.', 'additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Conditioner', 'product_type' => 'Haircare', 'description' => 'Haircare: Condtioner', 'price' => '7', 'ingredients' => 'Aqua / Water, Cetearyl Alcohol, Stearamidopropyl Dimethylamine, Isopropyl Myristate, Cetyl Esters, Parfum / Fragrance, Helianthus Annuus Seed Oil / Sunflower Seed Oil, Butyrospermum Parkii Butter / Shea Butter, Mel / Honey, Cera Alba / Beeswax, Caprylyl Glycol, Citric Acid, Tartaric Acid, Sodium Benzoate, Caramel, Coumarin, Limonene, Benzyl Alcohol, Benzyl Salicylate.', 'directions' => 'Smooth our conditioner generously into wet hair and rinse thoroughly. Use after our complementary shampoo for intense care.', 'additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Hair Mask', 'product_type' => 'Haircare', 'description' => 'Haircare: Mask', 'price' => '10', 'ingredients' => 'Aqua (Water/Eau), Cetearyl Alcohol, Behenamidopropyl Dimethylamine, Dicocoylethyl Hydroxyethylmonium Methosulfate, Butyrospermum Parkii (Shea) Butter, Lactic Acid, Mel (Honey/Miel), Propolis Cera (Propolis Wax/Cire de Propolis), Ceramide NP, Hydrolyzed Sodium Hyaluronate, Sodium Hyaluronate, Hydroxypropyltrimonium Hyaluronate, Panthenol, Squalane, Tocopherol, Glycerin, Ethylhexylglycerin, 1,2-Hexanediol, Sunflower Seed Oil Glycerides, Hydrogenated Ethylhexyl Olivate, Vitis Vinifera (Grape) Seed Oil, Carthamus Tinctorius (Safflower) Seed Oil, Calendula Officinalis Flower Extract, Hydrogenated Olive Oil Unsaponifiables, Oenothera Biennis (Evening Primrose) Oil, Rosa Canina Fruit Oil, Helianthus Annuus (Sunflower) Seed Oil, Helianthus Annuus (Sunflower) Sprout Extract, Citrus Aurantium Bergamia (Bergamot) Fruit Extract, Daucus Carota Sativa (Carrot) Root Extract, Caesalpinia Spinosa Fruit Extract, Parfum (Fragrance), Sodium Benzoate, Maltodextrin, Citrus Aurantium Peel Oil, Coumarin, Hexyl Cinnamal, Limonene, Linalool, Linalyl Acetate, Yellow 5 (CI 19140), Orange 4 (CI 15510).', 'directions' => 'After shampooing squeeze out excess water and apply evenly a generous amount over the lengths and ends of hair. Wait for 5-7 minutes then rinse thoroughly. Lightweight enough to use at every wash.', 'additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Hair Mousse', 'product_type' => 'Haircare', 'description' => 'Infused with Natural Avocado Oil, Pure Honey, Coconut Oil & Shea Butter, this smoothing and moisturising styling mousse eliminates fly aways for a flawless finish that last up to 72 hours.', 'price' => '10', 'ingredients' => 'Aqua/Water/Eau, PEG-40 Hydrogenated Castor Oil, Polyquaternium-11, PerseaGratissima (Avocado) Oil, Mel/Honey/Miel, Cocos Nucifera (Coconut) Oil, Butyrospermum Parkii(Shea) Butter, Caprylyl Glycol, Cocamidopropyl Betaine, Panthenol, PEG-40 Lanolin,Benzophenone-4, Parfum (Fragrance), Alpha-Isomethyl Ionone, Benzyl Salicylate,Hydroxycitronellal, Limonene, Linalool, Phenoxyethanol, Blue 1 (CI 42090), Yellow 5 (CI 19140).', 'directions' => 'Apply to damp or dry hair from ends to roots for definition. Allow hair to air dry or diffuse. Product can also be used to roller set, flexi rod set or twist out hair. Style as desired.', 'additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey-Infused Hair Oil', 'product_type' => 'Haircare', 'description' => 'Haircare: Hair Oil', 'price' => '8', 'ingredients' => 'Dimethicone, Dimethiconol, Trisiloxane, Mel (Honey/Miel), Helianthus Annuus Hybrid (Sunflower Seed) Oil, Vitis Vinifera (Grape) Seed Oil, Carthamus Tinctorius (Safflower) Seed Oil, Amaranthus Caudatus Seed Extract, Oenothera Biennis (Evening Primrose) Oil, Rosa Canina Fruit Oil, Calendula Officinalis Flower Extract, Citrus Aurantium Bergamia Fruit Extract, Daucus Carota Sativa Root Extract, Parfum (Fragrance), Tocopheryl Acetate, Tocopherol, Diisostearyl Malate, Coumarin, Hexyl Cinnamal, Limonene, Linalool, CI 26100 (Red 17), CI 47000 (Yellow 11).', 'directions' => 'Mix 2-3 full droppers of Honey Infused Hair Oil with a generous amount of HiveMind HoneyHair Mask. Apply the mixture from mid-lengths to ends - not on the scalp. Allow to absorb for 30 min, to deeply hydrate and strengthen. Always rinse out. For optimal results, repeat this treatment 2 times a week, or when necessary.', 'additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            
            ['product_name' => 'Honey Face Mask', 'product_type' => 'Skincare', 'description' => 'Hydrating and packed with the essentials your skin needs. ', 'price' => '12', 'ingredients' => 'Honey, Caprylic/Capric Triglyceride, PEG-7 Glyceryl Cocoate, Disteardimonium Hectorite, Helianthus Annuus Seed Oil, Macadamia Integrifolia Seed Oil, Cera Microcristallina, Pentylene Glycol, Polysorbate 20, Butyrospermum Parkii Butter, Cera Alba, Aqua, Tocopheryl Acetate, Corylus Avellana Seed Oil, Simmondsia Chinensis Seed Oil, Argania Spinosa Kernel Extract, Olus Oil, Glycerin, Bambusa Vulgaris Extract, Citrus Paradisi Fruit Extract, Eucalyptus Globulus Leaf Extract, Eugenia Caryophyllus Flower Extract, Punica Granatum Fruit Extract, Sophora Angustifolia Root Extract, Butylene Glycol, Phenoxyethanol, Aloe Barbadensis Leaf Water, Bambusa Vulgaris Water, Nelumbo Nucifera Flower Water, 1,2-Hexanediol, Propolis Extract, Snail Secretion Filtrate, Tocopherol, Arginine, Beta-Glucan, Bee Venom.', 'directions' => '1. After washing your face, spread all over face (avoid eyes). 2. Leave it for 10 minutes to a maximum of 1 hour. Rinse off with lukewarm water.', 'additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Moisturiser', 'product_type' => 'Skincare', 'description' => 'Skincare: Moisturiser', 'price' => '15', 'ingredients' => 'Helianthus Annus (Sunflower) Seed Oil, 100% Natural Cera Alba (Beeswax, Honey, Propolis and Pollen), Persea Gratissima (Avocado) Oil, Hydrogenated Avocado (Butter) Oil', 'directions' => 'null', 'additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Cleanser', 'product_type' => 'Skincare', 'description' => 'Skincare: Cleanser', 'price' => '15','ingredients' => 'GLYCERIN, HONEY/MEL/MIEL, MYRISTIC ACID, OLIVE OIL PEG-7 ESTERS, PAPAIN, POLYGLYCERYL-10 BEHENATE/EICOSADIOATE, ROYAL JELLY, CAMELLIA SINENSIS LEAF EXTRACT, POLYSORBATE 80, SODIUM LAURYL SULFOACETATE, PROPOLIS EXTRACT [EXTRAIT DE PROPOLIS], TRIETHANOLAMINE, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL.', 'directions' => 'null', 'additional_info' => 'null',  'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Lip Balm', 'product_type' => 'Skincare', 'description' => 'Your lips will stay hydrated and moisturised with our Honey Lip Balm. Enriched with sustainably-sourced honey and oils.', 'price' => '7', 'ingredients' => 'Ethylhexyl Palmitate, Tridecyl Trimellitate, Caprylic/Capric Triglyceride, Beeswax, Cocos Nucifera (Coconut) Oil, Aloe Barbadensis Leaf Extract, Olea Europaea (Olive) Fruit Oil, Hydroxystearic Acid, Tocopherol (Vitamin E), Hydrogenated Styrene/Isoprene Copolymer, Phenoxyethanol, Honey Extracts, Propolis Extracts, Aroma, CI 77492, CI 454101.', 'directions' => 'null','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Sunscreen SPF50', 'product_type' => 'Skincare', 'description' => 'Protect your skin barrier from UV rays with our Honey Sunscreen SPF50. Lightweight on your skin but highly protective against sunlight.', 'price' => '15', 'ingredients' => 'Aqua (Water), Zinc Oxide (nano), Ethylhexyl Methoxycinnamate, Caprylic/Capric Triglyceride, Octocrylene, Ethylhexyl Salicylate, Vitis Vinifera (Grape) Seed Oil, Cetearyl Alcohol, Glycerin, Jojoba Esters, Shea Butter Ethyl Esters, Betaine, Cocos Nucifera (Coconut) Oil, Glyceryl Stearate SE, Mel (Honey), Phenoxyethanol, Polyhydroxystearic Acid, Parfum (Fragrance), Potassium Cetyl Phosphate, Xylitylglucoside, Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Benzyl Alcohol, Anhydroxylitol, Ammonium Acryloyldimethyltaurate/VP Copolymer, Isohexadecane, Xylitol, Isostearic Acid, Xanthan Gum, Ethylhexylglycerin, Polysorbate 80, Dehydroacetic Acid, Sorbitan Oleate, Disodium EDTA, Bee Venom.', 'directions' => 'For daily use. Apply the sunscreen just before exposure. Re-apply frequently and generously to maintain protection. Avoid direct contact with eyes. We recommend a patch test before use. Do not use if you have an allergy to any of the listed ingredients. If irritation occurs discontinue use immediately.','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            
            ['product_name' => 'HiveMind Logo Sweatshirt', 'product_type' => 'Merchandise', 'description' => 'Minimalistic and sustainable, what’s not to love about this HiveMind Logo Sweatshirt, available in several colours.', 'price' => '30', 'ingredients' => '80% Cotton, 20% Polyester.', 'directions' => 'null','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'HiveMind Cap', 'product_type' => 'Merchandise', 'description' => 'Prepare for autumnal and winter weather with a HiveMind Cap to keep you warm, available in several colours.', 'price' => '15', 'ingredients' => '51% Cotton, 48% Polyester, 1% Rayon.', 'directions' => 'null','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'HiveMind T-Shirt', 'product_type' => 'Merchandise', 'description' => 'You can’t go wrong with a classic HiveMind T-Shirt. Suitable for any casual occasion and available in several colours.', 'price' => '18', 'ingredients' => '100% Cotton.', 'directions' => 'null','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'HiveMind Phone Case', 'product_type' => 'Merchandise', 'description' => 'Represent your support in saving the bees with the HiveMind Phone Case.', 'price' => '5', 'ingredients' => 'Hard Enamel, Rubber.', 'directions' => 'Attach the cover to the back of your phone to show off a stylish case.','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'HiveMind Tumbler', 'product_type' => 'Merchandise', 'description' => 'Stay hydrated year round, while supporting our bees with the HiveMind Tumbler.', 'price' => '7', 'ingredients' => 'Glass, plastic, and stainless steel', 'directions' => 'null','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
        ]);
        //
    }
}