<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            ['product_name' => 'Eyeshadow Pallete', 'product_type' => 'Beauty', 'description' => 'Beauty Product: Eyeshadow', 'price' => '8', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Lip Gloss', 'product_type' => 'Beauty', 'description' => 'Beauty Product: Lip Gloss', 'price' => '7', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Nail Polish (Set of 3)', 'product_type' => 'Beauty', 'description' => 'Beauty Product: Nail Polish', 'price' => '6', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => '2-in-1 Highlighter & Blush', 'product_type' => 'Beauty', 'description' => 'Beauty Product: Highlighter & Blush', 'price' => '7', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Beauty Sponge', 'product_type' => 'Beauty', 'description' => 'Beauty Product: Beauty Sponge', 'price' => '5', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Body Spray', 'product_type' => 'Beauty', 'description' => 'Stop and turn heads with HiveMind’s Honey Body Spray. Long-lasting and sweet, you’ll be craving more.', 'price' => '15', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Vitamin Bee (Vitamin B Gummies)', 'product_type' => 'Health', 'description' => 'Health and Wellness Product: Vitamin Gummy', 'price' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Bee Pollen Supplements', 'product_type' => 'Health', 'description' => 'Health and Wellness Product: Pollen Supplements', 'price' => '10', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Propolis Supplements', 'product_type' => 'Health', 'description' => 'Health and Wellness Product: Propolis Supplements', 'price' => '15', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Jar of Honey', 'product_type' => 'Health', 'description' => 'Health and Wellness Product: Jar of Honey', 'price' => '7', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Bee Pollen Powder 250g', 'product_type' => 'Health', 'description' => 'Health and Wellness Product: Pollen Powder 250g', 'price' => '15', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Shampoo', 'product_type' => 'Haircare', 'description' => 'Haircare: Shampoo', 'price' => '7', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Condtioner', 'product_type' => 'Haircare', 'description' => 'Haircare: Condtioner', 'price' => '7', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Hair Mask', 'product_type' => 'Haircare', 'description' => 'Haircare: Mask', 'price' => '10', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Hair Mousse', 'product_type' => 'Haircare', 'description' => 'Haircare: Mousse', 'price' => '10', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey-Infused Hair Oil', 'product_type' => 'Haircare', 'description' => 'Haircare: Hair Oil', 'price' => '8', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Face Mask', 'product_type' => 'Skincare', 'description' => 'Skincare: Face Mask', 'price' => '12', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Moisturiser', 'product_type' => 'Skincare', 'description' => 'Skincare: Moisturiser', 'price' => '15', 'created_at' => now(), 'updated_at' => now()],

            ['product_name' => 'Honey Cleanser', 'product_type' => 'Skincare', 'description' => 'Skincare: Cleanser', 'price' => '15','ingredients' => 'GLYCERIN, HONEY/MEL/MIEL, MYRISTIC ACID, OLIVE OIL PEG-7 ESTERS, PAPAIN, POLYGLYCERYL-10 BEHENATE/EICOSADIOATE, ROYAL JELLY, CAMELLIA SINENSIS LEAF EXTRACT, POLYSORBATE 80, SODIUM LAURYL SULFOACETATE, PROPOLIS EXTRACT [EXTRAIT DE PROPOLIS], TRIETHANOLAMINE, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL.', 'directions' => 'null','additional_info' => 'null',  'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Lip Balm', 'product_type' => 'Skincare', 'description' => 'Your lips will stay hydrated and moisturised with our Honey Lip Balm. Enriched with sustainably-sourced honey and oils.', 'price' => '7', 'ingredients' => 'Ethylhexyl Palmitate, Tridecyl Trimellitate, Caprylic/Capric Triglyceride, Beeswax, Cocos Nucifera (Coconut) Oil, Aloe Barbadensis Leaf Extract, Olea Europaea (Olive) Fruit Oil, Hydroxystearic Acid, Tocopherol (Vitamin E), Hydrogenated Styrene/Isoprene Copolymer, Phenoxyethanol, Honey Extracts, Propolis Extracts, Aroma, CI 77492, CI 454101.', 'directions' => 'null','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Sunscreen SPF50', 'product_type' => 'Skincare', 'description' => 'Protect your skin barrier from UV rays with our Honey Sunscreen SPF50. Lightweight on your skin but highly protective against sunlight.', 'price' => '15', 'ingredients' => 'Aqua (Water), Zinc Oxide (nano), Ethylhexyl Methoxycinnamate, Caprylic/Capric Triglyceride, Octocrylene, Ethylhexyl Salicylate, Vitis Vinifera (Grape) Seed Oil, Cetearyl Alcohol, Glycerin, Jojoba Esters, Shea Butter Ethyl Esters, Betaine, Cocos Nucifera (Coconut) Oil, Glyceryl Stearate SE, Mel (Honey), Phenoxyethanol, Polyhydroxystearic Acid, Parfum (Fragrance), Potassium Cetyl Phosphate, Xylitylglucoside, Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Benzyl Alcohol, Anhydroxylitol, Ammonium Acryloyldimethyltaurate/VP Copolymer, Isohexadecane, Xylitol, Isostearic Acid, Xanthan Gum, Ethylhexylglycerin, Polysorbate 80, Dehydroacetic Acid, Sorbitan Oleate, Disodium EDTA, Bee Venom.', 'directions' => 'For daily use. Apply the sunscreen just before exposure. Re-apply frequently and generously to maintain protection. Avoid direct contact with eyes. We recommend a patch test before use. Do not use if you have an allergy to any of the listed ingredients. If irritation occurs discontinue use immediately.','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'HiveMind Logo Hoodie', 'product_type' => 'Merchandise', 'description' => 'Minimalistic and sustainable, what’s not to love about this HiveMind Logo Hoodie, available in several colours.', 'price' => '30', 'ingredients' => '80% Cotton, 20% Polyester.', 'directions' => 'null','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'HiveMind Beenie', 'product_type' => 'Merchandise', 'description' => 'Prepare for autumnal and winter weather with a HiveMind Beenie to keep you warm, available in several colours.', 'price' => '15', 'ingredients' => '51% Cotton, 48% Polyester, 1% Rayon.', 'directions' => 'null','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'HiveMind T-Shirt', 'product_type' => 'Merchandise', 'description' => 'You can’t go wrong with a classic HiveMind T-Shirt. Suitable for any casual occasion and available in several colours.', 'price' => '18', 'ingredients' => '100% Cotton.', 'directions' => 'null','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'HiveMind Enamel Pin', 'product_type' => 'Merchandise', 'description' => 'Represent your support in saving the bees with the HiveMind Enamel Pin.', 'price' => '5', 'ingredients' => 'Hard Enamel, Rubber.', 'directions' => 'Remove the rubber clasp to attach the pin, and put it back on once the pin is secured in its desired position.','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'HiveMind Bee Socks', 'product_type' => 'Merchandise', 'description' => 'Complete a buzzing look with some HiveMind Bee Socks.', 'price' => '7', 'ingredients' => '69% Cotton, 28% Nylon, 3% Elastane.', 'directions' => 'null','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Lotion', 'product_type' => 'Bodycare', 'description' => 'Moisturise and hydrate your skin with our Honey Lotion. Ready to use after a relaxing shower or bath.', 'price' => '13', 'ingredients' => 'Aloe Barbadensis Leaf Juice, Aqua, Caprylic/Capric Triglyceride, Polyglyceryl-3 Methylglucose Distearate, Glycerin, Isocetyl Palmitate, Cetearyl Alcohol, Myristyl Myristate, Olea Europaea (Olive) Oil Unsaponifiables, Honey Extract (Manuka Extract), Theobroma Cacao Seed Butter, Butyrospermum Parkii Butter, Glyceryl Caprylate, Tocopherol, Helianthus Annuus Seed Oil, Glycyrrhetinic Acid, Retinyl Palmitate, Chondrus Crispus Extract, Xanthan Gum, Aroma, Sodium Benzoate, Potassium Sorbate, Sodium Phytate, Citric Acid.', 'directions' => 'null','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Shower Gel', 'product_type' => 'Bodycare', 'description' => 'Bodycare product: Honey Shower gel', 'price' => '15', 'ingredients' => 'Honey, Glycerine, Sodium Laureth Sulfate, Sodium Cocoamphoacetate, Geteme Tree Flower Honey, Perfume, Brazilian Orange Oil, Bergamot Oil, Titanium Dioxide, Amyl Cinnamal, Citronellol, Geraniol, Limonene, Linalool.', 'directions' => 'Rich honey soothes, hydrates and cleanses the skin as you lather with this addictively sweet shower gel. Rinse off and feel sweetly soft.','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Roll-On Deodorant', 'product_type' => 'Bodycare', 'description' => 'Bodycare product: Honey Roll-On Deodorant', 'price' => '9', 'ingredients' => 'Aloe Barbadensis Leaf Juice, Aqua, Zinc Ricinoleate, Triethyl Citrate, Lauryl Glucoside, Polyglyceryl-2 Dipolyhydroxystearate, Glycerin, Cetearyl Alcohol, Glyceryl Caprylate, Sodium Bicarbonate, Polyglyceryl-3 Stearate, Sodium Stearoyl Lactylate, Isocetyl Palmitate, Honey Extract (Manuka Honey), Cetraria Islandica Extract, Glycyrrhetinic Acid, Aroma, Tocopherol, Helianthus Annuus Seed Oil, Chondrus Crispus Extract, Xanthan Gum, Sodium Phytate, Sodium Benzoate, Potassium Sorbate, Citric Acid.', 'directions' => 'Allow product to dry before dressing.','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Body Scrub', 'product_type' => 'Bodycare', 'description' => 'Bodycare product: Honey Body Scrub', 'price' => '13', 'ingredients' => 'Sucrose, Petrolatum, Isopropyl Palmitate, Hydrated Silica, Fragrance(Parfum), Helianthus Annuus (Sunflower) Seed Oil, Persea Gratissima(Avocado) Oil, Honey (Mel, Miel), Prunus Amygdalus Dulcis (Sweet Almond)Oil, Phenoxyethanol, Carthamus Tinctorius (Safflower) Seed Oil, PrunusArmeniaca (Apricot) Kernel Oil, Styrene/Butadiene Copolymer, BHT, RicinusCommunis (Castor) Seed Oil, DMDM Hydantoin, Water (Aqua,Eau), Ethylhexylglycerin, Tocopheryl Acetate, PPG-26-Buteth-26,PEG-40Hydrogenated Castor Oil, Ethylhexyl Methoxycinnamate, ButylMethoxydibenzoylmethane, Ethylhexyl Salicylate, Annatto (CI 75120), Violet 2(CI 60725), Yellow 11 (CI 47000), Red 4 (CI 14700).', 'directions' => 'Apply the scrub to damp skin and massage your entire body in circular movements. Rinse with lukewarm water.','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Body Cream', 'product_type' => 'Bodycare', 'description' => 'Bodycare product: Honey Body Cream', 'price' => '16', 'ingredients' => 'Water, Decyl Cocoate, Glycerin, Helianthus Annuus (Sunflower) Seed Oil, Beeswax, Fragrance (Natural Fragrance), Butyrospermum Parkii (Shea) Butter, Cetyl Alcohol, Glyceryl Stearate Citrate, Polyglyceryl-3 Stearate, Cocos Nucifera (Coconut) Oil, Olea Europaea (Olive) Fruit Oil, Vitis Vinifera (Grape) Seed Oil, Nonfat Dry Milk, Honey, Aloe Barbadensis Leaf Juice, Rosmarinus Officinalis (Rosemary) Leaf Extract, Tocopherol, Beta-Carotene, Xanthan Gum, Sucrose Stearate, Glycine Soja (Soybean) Oil, Canola Oil, Lactic Acid, Citric Acid, Sodium Stearoyl Lactylate, Sodium Benzoate, Potassium Sorbate, Magnesium Aluminum Silicate, Phenoxyethanol, Benzyl Alcohol, Benzyl Benzoate, Benzyl Cinnamate, Citral, Coumarin, Limonene.', 'directions' => 'For best results, apply moisturising lotion liberally as needed all over your body.','additional_info' => 'null','created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Home Perfume Spray', 'product_type' => 'Home', 'description' => 'Home product: Honey Home Perfume Spray', 'price' => '18', 'ingredients' => 'Linalool, Linalyl acetate, Tetramethyl acetyloctahydronaphthalenes, Cedrol methyl ether, Cinnamal.', 'directions' => 'Open the nozzle by twisting it. Spray away from your face and body. Hold the container upright and spray with circular movements into the open space in the room. Close the nozzle by twisting it again. Store the product in the upright position.','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Scented Candle', 'product_type' => 'Home', 'description' => 'Home product: Honey Scented Candle', 'price' => '25', 'ingredients' => 'Cis-4-Tert-Butylcyclohexyl Acetate; Benzyl Salicylate; Citronellol; Piperonal; Linalyl Acetate; 1-(1,2,3,4,5,6,7,8-Octahydro-2;3;8;8-Tetramethyl-2-Naphthyl)Ethan-1-One; 3-Methyl-4-(2,6,6-Trimethyl-2-Cyclohexen-1-Yl)-3-Buten-2-One; 3-p-Cumenyl-2-Methylpropionaldehyde; Linalool; (E)-2-Methoxy-4-(Prop-1-Enyl) Phenol; (d)-Limonene; (2E)-2-(Phenylmethylidene)Octanal.', 'directions' => 'Allow it to burn for 3-4 hours to keep the wax from tunnelingand prevent the vessel from overheating. For best results, trim the wick before each use to maintain an ideal length of 5mm.','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Fragrance Sticks', 'product_type' => 'Home', 'description' => 'Home product: Honey Fragrance Sticks', 'price' => '18', 'ingredients' => '3-p-Cumenyl-2-Methylpropionaldehyde; Cis-4-Tert-Butylcyclohexyl Acetate; Citronellol; Coumarin; d-Limonene; Isoeugenol; Linalool; Linalyl Acetate; Piperonal.', 'directions' => 'Arrange the complementary sticks in your fragrance bottle and make sure to wash your hands afterwards. The fragrance sticks will give off a wonderful subtle fragrance without turning them around. However, if youd prefer a more intense perfume experience, the sticks can be turned more often to suit your preference.','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'Honey Refill Fragrance Sticks', 'product_type' => 'Home', 'description' => 'Home product: Honey Refill Fragrance Sticks', 'ingredients' => '3-p-Cumenyl-2-Methylpropionaldehyde; Cis-4-Tert-Butylcyclohexyl Acetate; Citronellol; Coumarin; d-Limonene; Isoeugenol; Linalool; Linalyl Acetate; Piperonal.', 'directions' => 'Fill your empty fragrance holder with the refill liquid. Always use fresh sticks with your refill and arrange them in the holder. If you prefer a more intense aroma, you can turn the sticks, but it isn’t necessary and may result in a shorter fragrance experience. If your hands come into contact with the liquid, wash them with water and soap.','additional_info' => 'null', 'price' => '22', 'created_at' => now(), 'updated_at' => now()],
            ['product_name' => 'HiveMind Beeswax Wraps', 'product_type' => 'Home', 'description' => 'Safely seal your food using our HiveMind Beeswax Wraps. Handmade with the utmost care.', 'price' => '15', 'ingredients' => 'OEKO-TEX Certified 100% Cotton, All-Natural Beeswax, Grade A Sustainably Tapped Damar Resin (Pine Resin-FREE), Extra-Virgin Olive Oil', 'directions' => 'Just like cling film, the wrap moulds around and adheres to surfaces or itself. The warmth of your hands makes the wrap pliable and adhesive. Don’t be afraid to pinch the ends together – that’s when it really does its job!Clean after each use with cold/cool water, a sponge and a little washing up liquid. Hang over your dish drying rack to air-dry.Don’t put it on any radiators or other heat sources or the wax will melt.Do not put into the microwave or oven, or wrap hot food/bowls.Can be used in the freezer or fridge.Not to be used on raw meat or fish.','additional_info' => 'null', 'created_at' => now(), 'updated_at' => now()],
        ]);
        //
    }
}
